version: '3'

services:
  redis:
    container_name: ${CONTAINER_REDIS_NAME}
    image: redis:3.0.7-alpine
    restart: unless-stopped

  postgresql:
    container_name: ${CONTAINER_DB_NAME}
    image: postgres:9.6.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
    volumes:
      - ${DB_PATH}:/var/lib/postgresql:rw

  gitlab:
    depends_on:
      - postgresql
      - redis
    container_name: ${CONTAINER_GITLAB_NAME}
    image: 'gitlab/gitlab-ce:9.1.0-ce.0'
    restart: unless-stopped
    volumes:
      - ${GL_CONFIG}:/etc/gitlab:rw
      - ${GL_LOGS}:/var/log/gitlab:rw
      - ${GL_DATA}:/var/opt/gitlab:rw
    ports:
      # both ports must match the port from external_url below
      - "${EXTERNAL_HTTP_PORT}:${EXTERNAL_HTTP_PORT}"
      # the mapped port must match ssh_port specified below.
      - "30022:${EXTERNAL_SSH_PORT}"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        postgresql['enable'] = false
        gitlab_rails['db_username'] = "${POSTGRESQL_USER}"
        gitlab_rails['db_password'] = "${POSTGRESQL_PASSWORD}"
        gitlab_rails['db_host'] = "postgresql"
        gitlab_rails['db_port'] = "5432"
        gitlab_rails['db_database'] = "${POSTGRESQL_DATABASE}"
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'utf8'
        redis['enable'] = false
        gitlab_rails['redis_host'] = 'redis'
        gitlab_rails['redis_port'] = '6379'
        external_url '${EXTERNAL_URL}'
        registry_external_url '${EXTERNAL_REGISTRY_URL}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${EXTERNAL_SSH_PORT}
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL} 

networks:
  default:
    external:
      name: ${NETWORK}
